export const metadata = {
    title: "Next.js",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body className={"bg-fuchsia-400"}>{children}
        </body>
      </html>
    );
  }